---
- name: SAMBA | Configure Samba file sharing
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: "0644"
  notify: Restart samba services
- name: SAMBA | Ensure Samba services are enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - smbd
    - nmbd
