---
- name: RCLONE | Install rclone package
  ansible.builtin.apt:
    name: rclone
    state: present
- name: RCLONE | Create .config/rclone directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.config/rclone
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
- name: RCLONE | Create rclone log file
  ansible.builtin.file:
    path: /var/log/rclone-upload.log
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
- name: RCLONE | Copy GCP Service Account Key to Pi
  ansible.builtin.copy:
    content: "{{ lookup('file', gcp_key_file) }}"
    dest: /home/{{ ansible_user }}/.config/rclone/service_account.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
- name: RCLONE | Configure rclone remote for Google Drive
  ansible.builtin.command:
    cmd: sudo -u {{ ansible_user }} rclone config create '{{ gdrive_remote_name }}' drive service_account_file='/home/{{ ansible_user }}/.config/rclone/service_account.json'
      root_folder_id='{{ gdrive_folder_id }}'
    changed_when: false
- name: RCLONE | Create systemd path and upload script
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    mode: "{{ item.mode | default('0644') }}"
    force: true
  loop:
    - { src: rclone-upload.service.j2, dest: /etc/systemd/system/rclone-upload.service }
    - { src: rclone-upload.path.j2, dest: /etc/systemd/system/rclone-upload.path }
    - { src: upload_logs.sh.j2, dest: /usr/local/bin/upload_logs.sh, mode: "0755" }
- name: RCLONE | Ensure rclone path watcher is enabled and started
  ansible.builtin.systemd:
    name: rclone-upload.path
    daemon_reload: true
    enabled: true
    state: started
